apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pw1j5upfu-go 
  janus-idp.io/tekton: pw1j5upfu-go
  backstage.io/kubernetes-id: pw1j5upfu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pw1j5upfu-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml