apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pw1j5upfu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pw1j5upfu-go 
  name: pw1j5upfu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pw1j5upfu-go 
